;;; hive-hagent.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(eval-and-compile (require 'clojure-elisp-runtime))
(require 'hive-hagent-log)
(require 'hive-hagent-backend)
(require 'hive-hagent-core)
(require 'hive-hagent-backend-openclaude)

;;; Code:



(defcustom hive-hagent-default-backend 'openclaude
  "Backend used by `hive-hagent' when no per-project override exists."
  :group 'hive-hagent
  :type '(choice (const openclaude) (const agent)))

(defvar hive-hagent--project-backends nil
  "Alist of (project-root . backend-name) overrides.")

(defun hive-hagent--resolve-backend-name ()
  "Return the backend symbol to use for the current project."
  (let* ((root (hive-hagent-core--current-project-root))
        (override (cdr (assoc root hive-hagent--project-backends))))
    (or override hive-hagent-default-backend)))

(defun hive-hagent--resolve-backend ()
  "Return the active backend plist for the current project."
  (let* ((name (hive-hagent--resolve-backend-name))
        (backend (hive-hagent-backend-get-backend name)))
    (unless backend
    (error "No hive-hagent backend registered under name %S" name))
    backend))

(defun hive-hagent--current-session ()
  "Return the live session for the current project + active backend, or nil."
  (let* ((root (hive-hagent-core--current-project-root))
        (name (hive-hagent--resolve-backend-name)))
    (hive-hagent-core-find-session root name)))

(defun hive-hagent-hive-hagent ()
  "Open (or reuse) a hagent chat for the current project."
  (interactive)
  (hive-hagent-core-open-session (hive-hagent--resolve-backend)))

(defun hive-hagent-hive-hagent-send (prompt)
  "Send PROMPT to the active hagent session for this project.\nStarts a session if none exists."
  (interactive "sPrompt: ")
  (let* ((session (or (hive-hagent--current-session) (hive-hagent-core-open-session (hive-hagent--resolve-backend)))))
    (hive-hagent-core-send-prompt session prompt)))

(defun hive-hagent-hive-hagent-send-region (beg end)
  "Send the region BEG..END as a prompt."
  (interactive "r")
  (hive-hagent-hive-hagent-send (buffer-substring-no-properties beg end)))

(defun hive-hagent-hive-hagent-interrupt ()
  "Interrupt the current turn in the active hagent session."
  (interactive)
  (let* ((session (hive-hagent--current-session)))
    (if session (hive-hagent-core-interrupt-session session) (message "hive-hagent: no active session"))))

(defun hive-hagent-hive-hagent-stop ()
  "Stop and tear down the hagent session for this project."
  (interactive)
  (let* ((session (hive-hagent--current-session)))
    (if session (hive-hagent-core-stop-session session) (message "hive-hagent: no active session"))))

(defun hive-hagent-hive-hagent-switch-backend ()
  "Pick a backend for the current project, remembered for this session."
  (interactive)
  (let* ((names (mapcar 'symbol-name (hive-hagent-backend-list-backends)))
        (choice (completing-read "hive-hagent backend: " names nil t))
        (sym (intern choice))
        (root (hive-hagent-core--current-project-root)))
    (setq hive-hagent--project-backends (cons (cons root sym) (assoc-delete-all root hive-hagent--project-backends)))
    (message "hive-hagent: %s active in %s" sym (or root "<global>"))))

(defun hive-hagent-hive-hagent-list-sessions ()
  "Show all live hagent sessions in the echo area."
  (interactive)
  (let* ((sessions (hive-hagent-core-active-sessions)))
    (if (null sessions) (message "hive-hagent: no active sessions") (message "hive-hagent: %d active session(s): %s" (length sessions) (mapconcat (lambda ()
    (format "%s/%s" (plist-get (plist-get s :backend) :name) (or (plist-get s :project-root) "<global>"))) sessions ", ")))))

(provide 'hive-hagent)

(provide 'hive-hagent)
;;; hive-hagent.el ends here
