;;; hive-hagent-core.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(eval-and-compile (require 'clojure-elisp-runtime))
(require 'hive-hagent-backend)
(require 'hive-hagent-log)

;;; Code:



(defgroup hive-hagent nil
  "Headed agent chat backends for Emacs."
  :group 'tools
  :prefix "hive-hagent-")

(defcustom hive-hagent-terminal-backend 'vterm
  "Terminal emulator to use when spawning CLI subprocesses.\nOne of: vterm, eat."
  :group 'hive-hagent
  :type '(choice (const vterm) (const eat)))

(defcustom hive-hagent-window-side 'right
  "Side of the frame to display the hagent window on."
  :group 'hive-hagent
  :type '(choice (const right) (const left) (const bottom) (const top)))

(defcustom hive-hagent-window-width 0.4
  "Fraction of frame width used by the hagent side window."
  :group 'hive-hagent
  :type 'float)

(defvar hive-hagent-core--sessions nil
  "Alist mapping (project-root . backend-name) -> session plist.")

(defun hive-hagent-core--session-key (project-root backend-name)
  "Registry key for a session."
  (cons (or project-root "<global>") backend-name))

(defun hive-hagent-core--buffer-name (project-root backend-name)
  "Canonical buffer name for a hagent session."
  (let* ((base (if project-root (file-name-nondirectory (directory-file-name project-root)) "global")))
    (format "*hagent:%s:%s*" (symbol-name backend-name) base)))

(defun hive-hagent-core--current-project-root ()
  "Return the project root for `default-directory', or nil."
  (let* ((proj (project-current)))
    (when proj
    (expand-file-name (project-root proj)))))

(defun hive-hagent-core--display-buffer (buf)
  "Pop BUF into a side window per `hive-hagent-window-side'."
  (display-buffer buf (list 'display-buffer-in-side-window (cons 'side hive-hagent-window-side) (cons 'window-width hive-hagent-window-width) '(slot . 0))))

(defun hive-hagent-core-find-session (project-root backend-name)
  "Look up a live session plist for PROJECT-ROOT + BACKEND-NAME, or nil."
  (let* ((existing (cdr (assoc (hive-hagent-core--session-key project-root backend-name) hive-hagent-core--sessions))))
    (when (and existing (buffer-live-p (plist-get existing :buffer)) (process-live-p (plist-get existing :process)))
    existing)))

(defun hive-hagent-core--register-session-bang (session)
  "Store SESSION in the registry, replacing any prior entry."
  (let* ((key (hive-hagent-core--session-key (plist-get session :project-root) (plist-get (plist-get session :backend) :name))))
    (setq hive-hagent-core--sessions (cons (cons key session) (assoc-delete-all key hive-hagent-core--sessions)))))

(defun hive-hagent-core--unregister-session-bang (session)
  "Drop SESSION from the registry."
  (let* ((key (hive-hagent-core--session-key (plist-get session :project-root) (plist-get (plist-get session :backend) :name))))
    (setq hive-hagent-core--sessions (assoc-delete-all key hive-hagent-core--sessions))))

(defun hive-hagent-core-open-session (backend)
  "Open (or reuse) a session for the current project using BACKEND plist.\nDisplays the buffer in the side window and returns the session plist."
  (let* ((root (hive-hagent-core--current-project-root))
        (name (plist-get backend :name))
        (existing (hive-hagent-core-find-session root name)))
    (if existing (progn
  (hive-hagent-core--display-buffer (plist-get existing :buffer))
  existing) (let* ((buf-name (hive-hagent-core--buffer-name root name))
        (result (hive-hagent-backend-start backend (list :project-root root :buffer-name buf-name :terminal hive-hagent-terminal-backend)))
        (session (list :backend backend :buffer (plist-get result :buffer) :process (plist-get result :process) :project-root root :created-at (current-time))))
    (hive-hagent-core--register-session-bang session)
    (hive-hagent-core--display-buffer (plist-get session :buffer))
    (hive-hagent-log-log-info 'core "started %s session for %s" name (or root "<global>"))
    session))))

(defun hive-hagent-core-send-prompt (session prompt)
  "Send PROMPT text to the CLI running in SESSION."
  (hive-hagent-backend-send (plist-get session :backend) (list :buffer (plist-get session :buffer) :process (plist-get session :process)) prompt))

(defun hive-hagent-core-interrupt-session (session)
  "Send an interrupt (ESC) to the CLI in SESSION."
  (hive-hagent-backend-interrupt (plist-get session :backend) (list :buffer (plist-get session :buffer) :process (plist-get session :process))))

(defun hive-hagent-core-stop-session (session)
  "Terminate SESSION's process and drop it from the registry."
  (hive-hagent-backend-stop (plist-get session :backend) (list :buffer (plist-get session :buffer) :process (plist-get session :process)))
  (hive-hagent-core--unregister-session-bang session)
  (hive-hagent-log-log-info 'core "stopped %s" (plist-get session :project-root)))

(defun hive-hagent-core-active-sessions ()
  "Return all live session plists."
  (mapcar 'cdr hive-hagent-core--sessions))

(provide 'hive-hagent-core)

(provide 'hive-hagent-core)
;;; hive-hagent-core.el ends here
