;;; hive-hagent-olympus.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(eval-and-compile (require 'clojure-elisp-runtime))
(require 'hive-hagent-backend)
(require 'hive-hagent-core)
(require 'hive-hagent-log)

;;; Code:



(defvar hive-hagent-swarm--slaves)

(defun hive-hagent-olympus-available-p ()
  "Non-nil if the olympus swarm registry is present (hive-emacs loaded)."
  (and (boundp 'hive-mcp-swarm--slaves) (hash-table-p (symbol-value 'hive-mcp-swarm--slaves))))

(defun hive-hagent-olympus--session-id (session)
  "Stable string id for SESSION — used as the swarm-registry key."
  (let* ((root (or (plist-get session :project-root) "global"))
        (backend-name (plist-get (plist-get session :backend) :name))
        (base (file-name-nondirectory (directory-file-name root))))
    (format "hagent:%s:%s" (symbol-name backend-name) base)))

(defun hive-hagent-olympus--session--gtslave (session status task)
  "Build a slave plist conforming to olympus-ui's expected schema."
  (list :id (hive-hagent-olympus--session-id session) :name (hive-hagent-olympus--session-id session) :buffer (plist-get session :buffer) :status status :current-task task :cwd (plist-get session :project-root) :kind 'hagent :backend (plist-get (plist-get session :backend) :name)))

(defun hive-hagent-olympus--put-bang (session status task)
  "Register / update SESSION in the olympus swarm table with STATUS."
  (when (hive-hagent-olympus-available-p)
    (let* ((id (hive-hagent-olympus--session-id session))
        (slave (hive-hagent-olympus--session--gtslave session status task)))
    (puthash id slave (symbol-value 'hive-mcp-swarm--slaves))
    (hive-hagent-log-log-debug 'olympus "put %s -> %s" id status))))

(defun hive-hagent-olympus--remove-bang (session)
  "Drop SESSION from the olympus swarm table."
  (when (hive-hagent-olympus-available-p)
    (let* ((id (hive-hagent-olympus--session-id session)))
    (remhash id (symbol-value 'hive-mcp-swarm--slaves))
    (hive-hagent-log-log-debug 'olympus "remove %s" id))))

(defun hive-hagent-olympus--after-open (session)
  "Register SESSION after `hive-hagent-core/open-session' returns."
  (hive-hagent-olympus--put-bang session ':idle nil)
  session)

(defun hive-hagent-olympus--after-send (session prompt)
  "Mark SESSION working after `hive-hagent-core/send-prompt'."
  (hive-hagent-olympus--put-bang session ':working prompt))

(defun hive-hagent-olympus--after-interrupt (session)
  "Return SESSION to idle after interrupt."
  (hive-hagent-olympus--put-bang session ':idle nil))

(defun hive-hagent-olympus--after-stop (session)
  "Unregister SESSION on stop."
  (hive-hagent-olympus--remove-bang session))

(defun hive-hagent-olympus-enable ()
  "Install advice so core lifecycle events propagate into olympus.\nQuoted symbols are NOT translated by the cljel compiler, so refer to\ncompiled elisp names directly (ns prefix + dash-separated)."
  (interactive)
  (advice-add 'hive-hagent-core-open-session :filter-return 'hive-hagent-olympus--after-open)
  (advice-add 'hive-hagent-core-send-prompt :after 'hive-hagent-olympus--after-send)
  (advice-add 'hive-hagent-core-interrupt-session :after 'hive-hagent-olympus--after-interrupt)
  (advice-add 'hive-hagent-core-stop-session :after 'hive-hagent-olympus--after-stop)
  (hive-hagent-log-log-info 'olympus "advice installed"))

(defun hive-hagent-olympus-disable ()
  "Remove advice installed by `enable'."
  (interactive)
  (advice-remove 'hive-hagent-core-open-session 'hive-hagent-olympus--after-open)
  (advice-remove 'hive-hagent-core-send-prompt 'hive-hagent-olympus--after-send)
  (advice-remove 'hive-hagent-core-interrupt-session 'hive-hagent-olympus--after-interrupt)
  (advice-remove 'hive-hagent-core-stop-session 'hive-hagent-olympus--after-stop)
  (hive-hagent-log-log-info 'olympus "advice removed"))

(hive-hagent-olympus-enable)

(provide 'hive-hagent-olympus)

(provide 'hive-hagent-olympus)
;;; hive-hagent-olympus.el ends here
