;;; hive-hagent-log.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(eval-and-compile (require 'clojure-elisp-runtime))

;;; Code:



(defgroup hive-hagent-log nil
  "Logging settings for hive-hagent."
  :group 'hive-hagent
  :prefix "hive-hagent-log-")

(defcustom hive-hagent-log-level 'info
  "Minimum log level to emit.  One of: debug, info, warn, error."
  :group 'hive-hagent-log
  :type '(choice (const debug) (const info) (const warn) (const error)))

(defvar hive-hagent-log--priority '((debug . 0) (info . 1) (warn . 2) (error . 3))
  "Level priority lookup.")

(defun hive-hagent-log--enabled-p (level)
  "Non-nil if LEVEL is at or above the configured minimum."
  (let* ((p (alist-get level hive-hagent-log--priority 1))
        (m (alist-get hive-hagent-log-level hive-hagent-log--priority 1)))
    (>= p m)))

(defun hive-hagent-log--emit (level component fmt args)
  "Format and print a log entry."
  (when (hive-hagent-log--enabled-p level)
    (let* ((label (upcase (symbol-name level)))
        (comp (if (stringp component) component (symbol-name component)))
        (msg (apply 'format fmt args)))
    (message "[hagent %s %s] %s" label comp msg))))

(defun hive-hagent-log-log-debug (component fmt &rest args)
  "Debug-level log message."
  (hive-hagent-log--emit 'debug component fmt args))

(defun hive-hagent-log-log-info (component fmt &rest args)
  "Info-level log message."
  (hive-hagent-log--emit 'info component fmt args))

(defun hive-hagent-log-log-warn (component fmt &rest args)
  "Warn-level log message."
  (hive-hagent-log--emit 'warn component fmt args))

(defun hive-hagent-log-log-error (component fmt &rest args)
  "Error-level log message."
  (hive-hagent-log--emit 'error component fmt args))

(provide 'hive-hagent-log)

(provide 'hive-hagent-log)
;;; hive-hagent-log.el ends here
