;;; hive-hagent-backend.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(eval-and-compile (require 'clojure-elisp-runtime))

;;; Code:



(defvar hive-hagent-backend--registry nil
  "Alist of (backend-name . backend-plist) for all registered backends.")

(defun hive-hagent-backend-register-bang (backend)
  "Register BACKEND plist.  Overwrites any existing entry with the same :name."
  (let* ((name (plist-get backend :name)))
    (setq hive-hagent-backend--registry (cons (cons name backend) (assq-delete-all name hive-hagent-backend--registry)))
    name))

(defun hive-hagent-backend-get-backend (name)
  "Look up backend by NAME symbol.  Returns plist or nil."
  (cdr (assq name hive-hagent-backend--registry)))

(defun hive-hagent-backend-list-backends ()
  "Return list of all registered backend names."
  (mapcar 'car hive-hagent-backend--registry))

(defun hive-hagent-backend-start (backend opts)
  "Start a session on BACKEND with OPTS.\nReturns {:buffer BUF :process PROC}."
  (funcall (plist-get backend :start-fn) opts))

(defun hive-hagent-backend-send (backend handle prompt)
  "Send PROMPT string to BACKEND session HANDLE."
  (funcall (plist-get backend :send-fn) handle prompt))

(defun hive-hagent-backend-interrupt (backend handle)
  "Interrupt the current turn on BACKEND session HANDLE."
  (funcall (plist-get backend :interrupt-fn) handle))

(defun hive-hagent-backend-stop (backend handle)
  "Stop and tear down BACKEND session HANDLE."
  (funcall (plist-get backend :stop-fn) handle))

(defun hive-hagent-backend-alive-p (backend handle)
  "Non-nil if BACKEND session HANDLE is still alive."
  (let* ((f (plist-get backend :alive-p-fn)))
    (if f (funcall f handle) (and (buffer-live-p (plist-get handle :buffer)) (process-live-p (plist-get handle :process))))))

(provide 'hive-hagent-backend)

(provide 'hive-hagent-backend)
;;; hive-hagent-backend.el ends here
