;;; hive-hagent.el --- -*- lexical-binding: t; -*-
;; Generated by ClojureElisp

(eval-and-compile (require 'clojure-elisp-runtime))
(require 'hive-hagent-log)
(require 'hive-hagent-backend)
(require 'hive-hagent-core)
(require 'hive-hagent-backend-openclaude)
(require 'hive-hagent-olympus)

;;; Code:



(defcustom hive-hagent-default-backend 'openclaude
  "Backend used by `hive-hagent' when no per-project override exists."
  :group 'hive-hagent
  :type '(choice (const openclaude) (const agent)))

(defvar hive-hagent--project-backends nil
  "Alist of (project-root . backend-name) overrides.")

(defun hive-hagent--resolve-backend-name ()
  "Return the backend symbol to use for the current project."
  (let* ((root (hive-hagent-core--current-project-root))
        (override (cdr (assoc root hive-hagent--project-backends))))
    (or override hive-hagent-default-backend)))

(defun hive-hagent--resolve-backend ()
  "Return the active backend plist for the current project."
  (let* ((name (hive-hagent--resolve-backend-name))
        (backend (hive-hagent-backend-get-backend name)))
    (unless backend
    (error "No hive-hagent backend registered under name %S" name))
    backend))

(defun hive-hagent--current-session ()
  "Return the live session for the current project + active backend, or nil."
  (let* ((root (hive-hagent-core--current-project-root))
        (name (hive-hagent--resolve-backend-name)))
    (hive-hagent-core-find-session root name)))

(defun hive-hagent-hive-hagent ()
  "Open (or reuse) a hagent chat for the current project."
  (interactive)
  (hive-hagent-core-open-session (hive-hagent--resolve-backend)))

(defun hive-hagent-hive-hagent-send (prompt)
  "Send PROMPT to the active hagent session for this project.\nStarts a session if none exists."
  (interactive "sPrompt: ")
  (let* ((session (or (hive-hagent--current-session) (hive-hagent-core-open-session (hive-hagent--resolve-backend)))))
    (hive-hagent-core-send-prompt session prompt)))

(defun hive-hagent-hive-hagent-send-region (beg end)
  "Send the region BEG..END as a prompt."
  (interactive "r")
  (hive-hagent-hive-hagent-send (buffer-substring-no-properties beg end)))

(defun hive-hagent-hive-hagent-interrupt ()
  "Interrupt the current turn in the active hagent session."
  (interactive)
  (let* ((session (hive-hagent--current-session)))
    (if session (hive-hagent-core-interrupt-session session) (message "hive-hagent: no active session"))))

(defun hive-hagent-hive-hagent-stop ()
  "Stop and tear down the hagent session for this project."
  (interactive)
  (let* ((session (hive-hagent--current-session)))
    (if session (hive-hagent-core-stop-session session) (message "hive-hagent: no active session"))))

(defun hive-hagent-hive-hagent-switch-backend ()
  "Pick a backend for the current project, remembered for this session."
  (interactive)
  (let* ((names (mapcar 'symbol-name (hive-hagent-backend-list-backends)))
        (choice (completing-read "hive-hagent backend: " names nil t))
        (sym (intern choice))
        (root (hive-hagent-core--current-project-root)))
    (setq hive-hagent--project-backends (cons (cons root sym) (assoc-delete-all root hive-hagent--project-backends)))
    (message "hive-hagent: %s active in %s" sym (or root "<global>"))))

(defun hive-hagent-hive-hagent-list-sessions ()
  "Show all live hagent sessions in the echo area."
  (interactive)
  (let* ((sessions (hive-hagent-core-active-sessions)))
    (if (null sessions) (message "hive-hagent: no active sessions") (message "hive-hagent: %d active session(s): %s" (length sessions) (mapconcat (lambda ()
    (format "%s/%s" (plist-get (plist-get s :backend) :name) (or (plist-get s :project-root) "<global>"))) sessions ", ")))))

(defcustom hive-hagent-keymap-prefix nil
  "Prefix key for `hive-hagent' commands.\nSet this in your init file before enabling `hive-hagent-mode'.\nExample: (setq hive-hagent-keymap-prefix (kbd \"C-c h\"))\nNote: Control-c <letter> is reserved for user bindings per Emacs\nconventions, which is exactly what this prefix is meant to be."
  :group 'hive-hagent
  :type '(choice (const :tag "None" nil) key-sequence))

(defvar hive-hagent-command-map (let* ((map (make-sparse-keymap)))
    (define-key map (kbd "h") 'hive-hagent/hive-hagent)
    (define-key map (kbd "s") 'hive-hagent/hive-hagent-send)
    (define-key map (kbd "r") 'hive-hagent/hive-hagent-send-region)
    (define-key map (kbd "i") 'hive-hagent/hive-hagent-interrupt)
    (define-key map (kbd "q") 'hive-hagent/hive-hagent-stop)
    (define-key map (kbd "b") 'hive-hagent/hive-hagent-switch-backend)
    (define-key map (kbd "l") 'hive-hagent/hive-hagent-list-sessions)
    map)
  "Keymap for `hive-hagent' commands, bound under `hive-hagent-keymap-prefix'.")

(defvar hive-hagent-mode-map (make-sparse-keymap)
  "Keymap for `hive-hagent-mode'.")

(defun hive-hagent-setup-keybindings ()
  "Install `hive-hagent-command-map' under `hive-hagent-keymap-prefix'.\nNo-op if the prefix is unset."
  (when hive-hagent-keymap-prefix
    (define-key hive-hagent-mode-map hive-hagent-keymap-prefix hive-hagent-command-map)))

(defvar hive-hagent-mode nil
  "Non-nil when `hive-hagent-mode' is enabled globally.")

(defun hive-hagent-hive-hagent-mode (&optional arg)
  "Toggle `hive-hagent-mode'.\nWith positive ARG enable, with non-positive ARG disable, otherwise toggle."
  (interactive "P")
  (let* ((enable (cond
  ((null arg) (not hive-hagent-hive-hagent-mode))
  ((and (numberp arg) (> arg 0)) t)
  (t nil))))
    (setq hive-hagent-mode enable)
    (if enable (progn
  (hive-hagent-setup-keybindings)
  (message "hive-hagent-mode enabled")) (message "hive-hagent-mode disabled"))))

(provide 'hive-hagent)

(provide 'hive-hagent)
;;; hive-hagent.el ends here
